server:
 port: 8080

spring:
  application:
     name: API-GATEWAY
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
      - id: userService
        uri: lb://USER-SERVICE
        predicates:
        - Path=/users/**
        filters:
        - name: CircuitBreaker
          args:
            name: userCircuitBreaker
            fallbackUri: forward:/fallback/user
                
      - id: orderService
        uri: lb://ORDER-SERVICE
        predicates:
        - Path=/orders/**
        filters:
        - name: CircuitBreaker
          args:
            name: orderCircuitBreaker
            fallbackUri: forward:/fallback/order
        
      - id: cartService
        uri: lb://CART-SERVICE
        predicates:
        - Path=/cart/**
        filters:
        - name: CircuitBreaker
          args:
            name: cartCircuitBreaker
            fallbackUri: forward:/fallback/cart
            
      - id: paymentService
        uri: lb://PAYMENT-SERVICE
        predicates:
        - Path=/payments/**
        filters:
        - name: CircuitBreaker
          args:
            name: paymentCircuitBreaker
            fallbackUri: forward:/fallback/payment

#Actuator

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always


#Details for info actuator

info:
   app:
      name: API Gateway
      description: Gateway to access Services
      version: 1.0.0
      
#Circuit Breaker

resilience4j:
  circuitbreaker:
    instances:
      CircuitBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    hostname: localhost
      